server:
  tomcat:
    url-encoding: UTF-8
  servlet:
    context-path: /
spring:
  application:
    name: edu-spring-data-jdbc
  profiles:
    active: local
  banner:
    location: "classpath:banner.txt"
# cache 사용을 위해 cache name 설정
  cache:
    cache-names: employee
#  security:
#    user:
#      name: admin
#      password: admin
#  boot:
#    admin:
#      client:
#        url: http://localhost:8080
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://211.252.87.34:40007/realms/employee-services # http://211.252.87.34:40007/realms/employee-services #http://211.252.87.34:40007/realms/company-services  # http://211.252.87.34:40007/realms/company-services

jwt:
  auth:
    converter:
      resource-id: edu-app # movies-app
      principal-attribute: preferred_username

app:
  cors:
    allowed-origins: http://localhost:3000
  keycloak:
    server : http://211.252.87.34:40007 # http://211.252.87.34:40007
  #  keycloak:
  #    auth-server-url: ${KEYCLOAK_SERVER_URL:http://localhost:8080/auth}
  #    realm: ${KEYCLOAK_REALM:spring-boot-blueprint}
  #    resource: ${KEYCLOAK_RESOURCE:spring-boot-app}
  #    public-client: true
  #    ssl-required: ${KEYCLOAK_SSL_REQUIRED:external}
  #    principal-attribute: preferred_username
  #    confidential-port: ${KEYCLOAK_CONFIDENTIAL_PORT:443}

# logging
logging:
  config: classpath:log4j2.xml

#jasypt encryptor
jasypt:
  encryptor:
    bean: jasyptStringEncryptor

#jwt:
#  secret: edujwt

# app
app-info:
  app-name: "edu-spring-data-jdbc"
  title: "Cloud Native Edu API"
  build:
    version: '@project.version@'
    timestamp: '@app.build.timestamp@'
  user-id: "jake lee"
  org-id: "KT"
  desc: "EDU 관련 설명입니다."
  doc-url: "https://github.com/kt-cloudnative/education/"
  license: "Apache License"
  license_url: "https://github.com/kt-cloudnative/education/"
  version: "@app.build.timestamp@"
  doc-desc: "교육용"

